### ISSUE TITLE
Wykres "Liczba sędziów w czasie" ma zły tytuł

### ISSUE THREAD

**Issue by mbojan** [saos-apps/wspolzasiadanie#15]
Jest "Wykres pokazujący liczbę orzeczeń..." a powinno być Wykres pokazujący liczbę sędziów orzekających w danym miesiącu. Etykieta OY też jest niepoprawna. Może takie nazwy:
- Tytuł w menu: "Liczba orzekających sędziów"
- Tytuł wykresu: j/w
- OX: Miesiące.
- OY: Liczba orzekających sędziów.
- Opis wykresu (być może rozszerzymy potem): Wykres przedstawia liczbe sędziów, którzy byli członkami przynajmniej jednego składu orzekającego na wydanym orzeczeniu.

**Comment by PatrykSkowron** [comment]
poprawione
