### ISSUE TITLE
jedna sieć dla jednego sądu

### ISSUE THREAD

**Issue by mbojan** [saos-apps/wspolzasiadanie#2]
kolory wg izb/wydziałów wydających orzeczenie

**Comment by PatrykSkowron** [comment]
Aktualnie są 2 wizualizacje:

z mark group - przy dużej liczbie wydziałów nieczytelna sieć, ale pokazuje płeć na wierzchołkach 
z wierzchołkami różnokolorowymi wg. wydziałów - bardziej czytelne ale tracimy informacje o płci.

Trzeba zdecydować które lepsze czy poszukać jakiegoś rozwiązania pośredniego
