### ISSUE TITLE
statystyki i wykresy

### ISSUE THREAD

**Issue by mbojan** [saos-apps/wspolzasiadanie#3]
Statystyki:
- rozkład wielkości składów orzekających (liczba orzeczeń)
- liczba orzeczeń w czasie
- płeć sędziego na sieci
- dotchart liczby rozsądzanych dla 10 "topowych" sędziów

**Comment by PatrykSkowron** [comment]
dodane, czy są wystarczająco czytelne?

**Comment by mbojan** [comment]
Patrz #10 o niesieciowych wykresach.
